package com.tgh.dnswizard.bean;

import de.greenrobot.dao.DaoException;

import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CITY.
 */
public class City {

    private Long id;
    /** Not-null value. */
    private String text;
    private long provinceId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient CityDao myDao;

    private Province province;
    private Long province__resolvedKey;

    private List<DNS> dnsList;

    public City() {
    }

    public City(Long id) {
        this.id = id;
    }

    public City(Long id, String text, long provinceId) {
        this.id = id;
        this.text = text;
        this.provinceId = provinceId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getCityDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(String text) {
        this.text = text;
    }

    public long getProvinceId() {
        return provinceId;
    }

    public void setProvinceId(long provinceId) {
        this.provinceId = provinceId;
    }

    /** To-one relationship, resolved on first access. */
    public Province getProvince() {
        long __key = this.provinceId;
        if (province__resolvedKey == null || !province__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ProvinceDao targetDao = daoSession.getProvinceDao();
            Province provinceNew = targetDao.load(__key);
            synchronized (this) {
                province = provinceNew;
            	province__resolvedKey = __key;
            }
        }
        return province;
    }

    public void setProvince(Province province) {
        if (province == null) {
            throw new DaoException("To-one property 'provinceId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.province = province;
            provinceId = province.getId();
            province__resolvedKey = provinceId;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<DNS> getDnsList() {
        if (dnsList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            DNSDao targetDao = daoSession.getDNSDao();
            List<DNS> dnsListNew = targetDao._queryCity_DnsList(id);
            synchronized (this) {
                if(dnsList == null) {
                    dnsList = dnsListNew;
                }
            }
        }
        return dnsList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetDnsList() {
        dnsList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        City city = (City) o;

        if (provinceId != city.provinceId) return false;
        if (!id.equals(city.id)) return false;
        if (!text.equals(city.text)) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = id.hashCode();
        result = 31 * result + text.hashCode();
        result = 31 * result + (int) (provinceId ^ (provinceId >>> 32));
        return result;
    }

    @Override
    public String toString() {
        return text;
    }
}
