package com.tgh.dnswizard.bean;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.tgh.dnswizard.bean.ISP;
import com.tgh.dnswizard.bean.Province;
import com.tgh.dnswizard.bean.City;
import com.tgh.dnswizard.bean.DNS;

import com.tgh.dnswizard.bean.ISPDao;
import com.tgh.dnswizard.bean.ProvinceDao;
import com.tgh.dnswizard.bean.CityDao;
import com.tgh.dnswizard.bean.DNSDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig iSPDaoConfig;
    private final DaoConfig provinceDaoConfig;
    private final DaoConfig cityDaoConfig;
    private final DaoConfig dNSDaoConfig;

    private final ISPDao iSPDao;
    private final ProvinceDao provinceDao;
    private final CityDao cityDao;
    private final DNSDao dNSDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        iSPDaoConfig = daoConfigMap.get(ISPDao.class).clone();
        iSPDaoConfig.initIdentityScope(type);

        provinceDaoConfig = daoConfigMap.get(ProvinceDao.class).clone();
        provinceDaoConfig.initIdentityScope(type);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        dNSDaoConfig = daoConfigMap.get(DNSDao.class).clone();
        dNSDaoConfig.initIdentityScope(type);

        iSPDao = new ISPDao(iSPDaoConfig, this);
        provinceDao = new ProvinceDao(provinceDaoConfig, this);
        cityDao = new CityDao(cityDaoConfig, this);
        dNSDao = new DNSDao(dNSDaoConfig, this);

        registerDao(ISP.class, iSPDao);
        registerDao(Province.class, provinceDao);
        registerDao(City.class, cityDao);
        registerDao(DNS.class, dNSDao);
    }
    
    public void clear() {
        iSPDaoConfig.getIdentityScope().clear();
        provinceDaoConfig.getIdentityScope().clear();
        cityDaoConfig.getIdentityScope().clear();
        dNSDaoConfig.getIdentityScope().clear();
    }

    public ISPDao getISPDao() {
        return iSPDao;
    }

    public ProvinceDao getProvinceDao() {
        return provinceDao;
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public DNSDao getDNSDao() {
        return dNSDao;
    }

}
